config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :link_specialty_disciplines
  resources :specialties
  resources :disciplines

  get 'disciplines/by_specialty/:id' => 'disciplines#by_specialty'

  root 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/specialties/:id' => 'specialties#show'
  get '/specialties/compare/:id/:comparison_id' => 'specialties#compare'

  namespace :api do
    resources :specialties do
      get 'disciplines', on: :member
      get 'group_list', on: :collection
      get :search, on: :collection
    end
    get 'disciplines' => 'disciplines#index'
    get 'disciplines/compare' => 'disciplines#compare'
  end
end

app/models/discipline.rb
# == Schema Information
#
# Table name: disciplines
#
#  id            :integer          not null, primary key
#  name          :string
#  label         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  zet           :float
#  practice?     :boolean
#  department_id :integer
#  human_label   :string
#

class Discipline < ApplicationRecord
  has_many :link_specialty_disciplines
  has_many :specialties, -> { distinct }, through: :link_specialty_disciplines
  belongs_to :department

  ### Scopes
  # module scopes
  scope :main, -> { where("label ILIKE '%1-%'") }
  scope :practice, -> { where("label ILIKE '%2-%'") }
  scope :others, -> { where("label ILIKE '%3-%'") }


  # profile scopes
  scope :humanitarian, -> { where("label ILIKE '%-ГМ%'") }
  scope :general_sciencific, -> { where("label ILIKE '%-ОНМ%'") }
  scope :general_professional, -> { where("label ILIKE '%-ОПМ%'") }
  scope :professional, -> { where("label ILIKE '%-ПМ.%'") }
  scope :naturally_sciencific, -> { where("label ILIKE '%-ЕНМ%'") }
  scope :inf_legal, -> { where("label ILIKE '%-ИПМ%'") }

  # type scopes
  scope :basic, -> { where("label ILIKE '%.Б.%'") }
  scope :variable, -> { where("label ILIKE '%.В.%'") }
  scope :variable_obligatory, -> { where("label ILIKE '%.В.ОД%'") }
  scope :variable_elective, -> { where("label ILIKE '%.В.ДВ%'") }

  scope :with_links, -> {
    joins(:link_specialty_disciplines)
    .select("
      disciplines.*,string_agg(DISTINCT link_specialty_disciplines.human_htype::varchar,',') as htypes,
      string_agg(DISTINCT link_specialty_disciplines.human_short_htype::varchar,',') as short_htypes,
      string_agg(DISTINCT link_specialty_disciplines.term_number::varchar,',') as terms,
      json_object(array_agg(link_specialty_disciplines.human_short_htype::text), array_agg(link_specialty_disciplines.hours::text)) as hours
    ")
    .group(:id)
  }

  scope :compare, -> (specialty_ids, term_number) {
    joins(:link_specialty_disciplines)
    .select("
      DISTINCT ON (disciplines.id) disciplines.*,
      string_agg(DISTINCT link_specialty_disciplines.human_htype::varchar,',') as htypes,
      string_agg(DISTINCT link_specialty_disciplines.human_short_htype::varchar,',') as short_htypes,
      (SELECT
        json_object(array_agg(ls.human_short_htype::text), array_agg(ls.hours::text))
        FROM link_specialty_disciplines as ls
        WHERE ls.specialty_id = #{specialty_ids[0]}
        AND ls.discipline_id=disciplines.id
        AND ls.term_number=#{term_number})
      as first,
      (SELECT
        json_object(array_agg(ls.human_short_htype::text), array_agg(ls.hours::text))
        FROM link_specialty_disciplines as ls
        WHERE ls.specialty_id= #{specialty_ids[1]}
        AND ls.discipline_id = disciplines.id
        AND ls.term_number=#{term_number})
      as second
    ")
    .select("link_specialty_disciplines.specialty_id, link_specialty_disciplines.discipline_id")
    .group(
      "link_specialty_disciplines.specialty_id,
      link_specialty_disciplines.discipline_id"
    )
    .where(link_specialty_disciplines: { specialty_id: specialty_ids, term_number: term_number })
    .group(:id)
  }

  scope :with_links_by_params, -> (params={}) { with_links.where_by_params(params) }

  scope :with_links_id, -> {
    with_links
    .select("link_specialty_disciplines.specialty_id, link_specialty_disciplines.discipline_id")
    .group("
    link_specialty_disciplines.specialty_id,
    link_specialty_disciplines.discipline_id"
    )
  }

  def self.where_by_params(filters={})
    params = filters.symbolize_keys
    where_query = [].tap do |filter|
      filter << "link_specialty_disciplines.specialty_id = #{params[:specialty_id]}"
      filter << "link_specialty_disciplines.term_number = #{params[:term_number]}" if params[:term_number].present?
    end

    where(where_query.join(" AND "))
  end

  ### methods and helpers
  # def human_label
  #   case
  #   when label.include?("-ГМ")
  #     "Гуманитарный"
  #   when label.include?("-ОНМ")
  #     "Общенаучный"
  #   when label.include?("-ОПМ")
  #     "Общепрофессиональный"
  #   when label.include?("-ПМ")
  #     "Профессиональный"
  #   when label.include?("-ЕНМ")
  #     "Естественнонаучный"
  #   when label.include?("-ИПМ")
  #     "Информационно-правовой"
  #   else
  #     "Другое"
  #   end
  # end

  def sorted_short_htype
    order = ['Лек', 'Лаб', 'Пр', 'СРС', 'КСР', 'К/п', 'К/р', 'Зач', 'Экз']
    ApplicationController.helpers.custom_sort(short_htypes.split(','), order)
  end
end

app/controllers/api/disciplines_controller.rb
module Api
  class DisciplinesController < ApplicationController
    before_action :check_params, only: :index
    before_action :get_disciplines, only: :compare

    def index
      render json: @disciplines.sort{ |a, b| [a.human_label, a.name] <=> [b.human_label, b.name] }.to_json(methods: [:human_label, :sorted_short_htype])
    end

    def compare
      render json: {
        similar: JSON.parse(@similar.sort{ |a, b| [a.human_label, a.name] <=> [b.human_label, b.name] }.to_json(methods: [:human_label, :sorted_short_htype])),
        different: JSON.parse(@different.sort{ |a, b| [a.human_label, a.name] <=> [b.human_label, b.name] }.to_json(methods: [:human_label, :sorted_short_htype])) }
    end

    def check_params
      @disciplines = if params.include?('specialty_id')
        Discipline.with_links_by_params(specialty_id: params[:specialty_id], term_number: params[:term_number])
      else
        Discipline.with_links
      end
    end

    def get_disciplines
      disciplines = Discipline.compare(params[:specialty_ids], params[:term_number])
      @similar = disciplines.select { |discipline| discipline['first'].present? && discipline['second'].present? }
      @different = disciplines.select { |discipline| discipline['first'].blank? || discipline['second'].blank? }
    end
  end
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_specialties, only: [:by_specialty]

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.all
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  def by_specialty
    @specialty_id = params[:id]
    respond_to do |format|
      format.html
      format.js
      format.json # { render json: @disciplines.as_json }
    end
  end
  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:name, :label)
    end

    def set_specialties
      # rewrite this on scopes in model
      base_query = LinkSpecialtyDiscipline.joins(:discipline).select("link_specialty_disciplines.*, disciplines.name || ' ' || disciplines.label as name, disciplines.id as d_id").where(link_specialty_disciplines: { specialty_id: params[:id] })

      natural_science_cond = "disciplines.label ILIKE '%-ЕНМ.%'"
      humanities_cond = "disciplines.label ILIKE '%-ГМ.%'"

      @natural_science_disciplines = to_strict(base_query.where(natural_science_cond).group_by(&:name).sort)
      @humanities_science_disciplines = to_strict(base_query.where(humanities_cond).group_by(&:name).sort)
      @special_disciplines = to_strict(base_query.where.not(natural_science_cond).where.not(humanities_cond).group_by(&:name).sort)
    # Discipline.joins(:link_specialty_disciplines).where(link_specialty_disciplines: { specialty_id: params[:id] })
    end

    def to_strict(ar_array)
      ar_array.map {|d| OpenStruct.new(id: d[1].first.try(:discipline_id), name: d[0], courses: d[1]) }
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.haml
= form_for @discipline do |f|
  - if @discipline.errors.any?
    #error_explanation
      %h2= "#{pluralize(@discipline.errors.count, "error")} prohibited this discipline from being saved:"
      %ul
        - @discipline.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :label
    = f.text_field :label
  .actions
    = f.submit 'Save'

app/views/disciplines/_index.html.haml
.row
- if @natural_science_disciplines.present?
  .col-md-4
    %h3
      Естественно-научные
      %span.text-danger
        =@natural_science_disciplines.size

    - @natural_science_disciplines.each do |discipline|
      .card.card-outline-danger
        .card-block
          %blockquote.card-blockquote
            %div
              = link_to "#{discipline.name}", discipline_path(discipline.id)
            - discipline.courses.each do |course|
              %div
                = course.human_htype
                \|
                = course.hours
                часов

- if @humanities_science_disciplines.present?
  .col-md-4
    %h3
      Гуманитарные
      %span.text-success
        =@humanities_science_disciplines.size

    - @humanities_science_disciplines.each do |discipline|
      .card.card-outline-success
        .card-block
          %blockquote.card-blockquote
            %div
              = link_to "#{discipline.name}", discipline_path(discipline.id)
            - discipline.courses.each do |course|
              %div
                = course.human_htype
                \|
                = course.hours
                часов

- if @special_disciplines.present?
  .col-md-4
    %h3
      Специальные
      %span.text-info
        =@special_disciplines.size

    - @special_disciplines.each do |discipline|
      .card.card-outline-info
        .card-block
          %blockquote.card-blockquote
            %div
              = link_to "#{discipline.name}", discipline_path(discipline.id)
            - discipline.courses.each do |course|
              %div
                = course.human_htype
                \|
                = course.hours
                часов

= link_to 'New Discipline', new_discipline_path

app/views/disciplines/by_specialty.js.erb
$("#list-<%= @specialty_id %>").empty()
$("#list-<%= @specialty_id %>").append("<%= j render 'disciplines/index' %>");
$('.disciplines-list').click(function(e) { e.stopPropagation(); })

app/views/disciplines/edit.html.haml
%h1 Editing discipline

= render 'form'

= link_to 'Show', @discipline
\|
= link_to 'Back', disciplines_path

app/views/disciplines/index.html.haml
%h1 Listing disciplines

%table
  %thead
    %tr
      %th Name
      %th Label
      %th
      %th
      %th

  %tbody
    - @disciplines.each do |discipline|
      %tr
        %td= discipline.name
        %td= discipline.label
        %td= link_to 'Show', discipline
        %td= link_to 'Edit', edit_discipline_path(discipline)
        %td= link_to 'Destroy', discipline, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Discipline', new_discipline_path

app/views/disciplines/new.html.haml
%h1 New discipline

= render 'form'

= link_to 'Back', disciplines_path

app/views/disciplines/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @discipline.name
%p
  %b Label:
  = @discipline.label

- if current_user
  = link_to 'Edit', edit_discipline_path(@discipline)
  \|
  = link_to 'Back', disciplines_path