config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :link_specialty_disciplines
  resources :specialties
  resources :disciplines

  get 'disciplines/by_specialty/:id' => 'disciplines#by_specialty'

  root 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/specialties/:id' => 'specialties#show'
  get '/specialties/compare/:id/:comparison_id' => 'specialties#compare'

  namespace :api do
    resources :specialties do
      get 'disciplines', on: :member
      get 'group_list', on: :collection
      get :search, on: :collection
    end
    get 'disciplines' => 'disciplines#index'
    get 'disciplines/compare' => 'disciplines#compare'
  end
end

app/models/link_specialty_discipline.rb
# == Schema Information
#
# Table name: link_specialty_disciplines
#
#  id                :integer          not null, primary key
#  term              :integer
#  htype             :integer
#  human_htype       :string
#  specialty_id      :integer
#  discipline_id     :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  hours             :integer
#  human_short_htype :string
#  term_number       :integer
#

class LinkSpecialtyDiscipline < ApplicationRecord
  belongs_to :specialty
  belongs_to :discipline
end

app/controllers/link_specialty_disciplines_controller.rb
class LinkSpecialtyDisciplinesController < ApplicationController
  before_action :set_link_specialty_discipline, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  # GET /link_specialty_disciplines
  # GET /link_specialty_disciplines.json
  def index
    @link_specialty_disciplines = LinkSpecialtyDiscipline.all
  end

  # GET /link_specialty_disciplines/1
  # GET /link_specialty_disciplines/1.json
  def show
  end

  # GET /link_specialty_disciplines/new
  def new
    @link_specialty_discipline = LinkSpecialtyDiscipline.new
  end

  # GET /link_specialty_disciplines/1/edit
  def edit
  end

  # POST /link_specialty_disciplines
  # POST /link_specialty_disciplines.json
  def create
    @link_specialty_discipline = LinkSpecialtyDiscipline.new(link_specialty_discipline_params)

    respond_to do |format|
      if @link_specialty_discipline.save
        format.html { redirect_to @link_specialty_discipline, notice: 'Link specialty discipline was successfully created.' }
        format.json { render :show, status: :created, location: @link_specialty_discipline }
      else
        format.html { render :new }
        format.json { render json: @link_specialty_discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /link_specialty_disciplines/1
  # PATCH/PUT /link_specialty_disciplines/1.json
  def update
    respond_to do |format|
      if @link_specialty_discipline.update(link_specialty_discipline_params)
        format.html { redirect_to @link_specialty_discipline, notice: 'Link specialty discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @link_specialty_discipline }
      else
        format.html { render :edit }
        format.json { render json: @link_specialty_discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /link_specialty_disciplines/1
  # DELETE /link_specialty_disciplines/1.json
  def destroy
    @link_specialty_discipline.destroy
    respond_to do |format|
      format.html { redirect_to link_specialty_disciplines_url, notice: 'Link specialty discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link_specialty_discipline
      @link_specialty_discipline = LinkSpecialtyDiscipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_specialty_discipline_params
      params.require(:link_specialty_discipline).permit(:term, :htype, :human_htype, :specialty_id, :discipline_id)
    end
end

app/helpers/link_specialty_disciplines_helper.rb
module LinkSpecialtyDisciplinesHelper
	def specialty_options(selected)
		options_for_select(Specialty.all.map{ |sp| ["#{sp.human_dtype} #{sp.direction} #{sp.human_level} #{sp.human_study_form} ", sp.id] }, selected)
	end

	def discipline_options(selected)
		options_for_select(Discipline.all.map{ |ds| ["#{ds.name} #{ds.label}", ds.id] }, selected)
	end

end

app/views/link_specialty_disciplines/_form.html.haml
= form_for @link_specialty_discipline do |f|
  - if @link_specialty_discipline.errors.any?
    #error_explanation
      %h2= "#{pluralize(@link_specialty_discipline.errors.count, "error")} prohibited this link_specialty_discipline from being saved:"
      %ul
        - @link_specialty_discipline.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :term
    = f.number_field :term
  .field
    = f.label :htype
    = f.number_field :htype
  .field
    = f.label :human_htype
    = f.text_field :human_htype
  .field
    = f.label :specialty
    = f.select(:specialty_id, specialty_options(f.object.specialty_id))
  .field
    = f.label :discipline
    = f.select(:discipline_id, discipline_options(f.object.discipline_id))
  .actions
    = f.submit 'Save'

app/views/link_specialty_disciplines/edit.html.haml
%h1 Editing link_specialty_discipline

= render 'form'

= link_to 'Show', @link_specialty_discipline
\|
= link_to 'Back', link_specialty_disciplines_path

app/views/link_specialty_disciplines/index.html.haml
%h1 Listing link_specialty_disciplines

%table
  %thead
    %tr
      %th Term
      %th Htype
      %th Human htype
      %th Specialty
      %th Discipline
      %th
      %th
      %th

  %tbody
    - @link_specialty_disciplines.each do |link_specialty_discipline|
      %tr
        %td= link_specialty_discipline.term
        %td= link_specialty_discipline.htype
        %td= link_specialty_discipline.human_htype
        %td= link_specialty_discipline.specialty.direction
        %td= link_specialty_discipline.discipline.name
        %td= link_to 'Show', link_specialty_discipline
        %td= link_to 'Edit', edit_link_specialty_discipline_path(link_specialty_discipline)
        %td= link_to 'Destroy', link_specialty_discipline, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Link specialty discipline', new_link_specialty_discipline_path

app/views/link_specialty_disciplines/new.html.haml
%h1 New link_specialty_discipline

= render 'form'

= link_to 'Back', link_specialty_disciplines_path

app/views/link_specialty_disciplines/show.html.haml
%p#notice= notice

%p
  %b Term:
  = @link_specialty_discipline.term
%p
  %b Htype:
  = @link_specialty_discipline.htype
%p
  %b Human htype:
  = @link_specialty_discipline.human_htype
%p
  %b Specialty:
  = @link_specialty_discipline.specialty
%p
  %b Discipline:
  = @link_specialty_discipline.discipline

= link_to 'Edit', edit_link_specialty_discipline_path(@link_specialty_discipline)
\|
= link_to 'Back', link_specialty_disciplines_path