config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :link_specialty_disciplines
  resources :specialties
  resources :disciplines

  get 'disciplines/by_specialty/:id' => 'disciplines#by_specialty'

  root 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/specialties/:id' => 'specialties#show'
  get '/specialties/compare/:id/:comparison_id' => 'specialties#compare'

  namespace :api do
    resources :specialties do
      get 'disciplines', on: :member
      get 'group_list', on: :collection
      get :search, on: :collection
    end
    get 'disciplines' => 'disciplines#index'
    get 'disciplines/compare' => 'disciplines#compare'
  end
end

app/models/sae.rb
# == Schema Information
#
# Table name: saes
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sae < ApplicationRecord
  has_many :specialties
  has_many :departments_saes
  has_many :departments, through: :departments_saes
  # has_many :specialties, -> { joins("INNER JOIN departments_saes ON specialties.department_id = departments_saes.department_id INNER JOIN saes ON saes.id = departments_saes.sae_id") }, foreign_key: "department_id"

  # def specialties
  #   Specialty.joins("INNER JOIN departments_saes ON specialties.department_id = departments_saes.department_id AND departments_saes.sae_id = #{id}")
  # end

  def disciplines
    Discipline.joins("INNER JOIN departments_saes ON disciplines.department_id = departments_saes.department_id AND departments_saes.sae_id = #{id}")
  end
end

app/models/specialty.rb
# == Schema Information
#
# Table name: specialties
#
#  id               :integer          not null, primary key
#  dtype            :integer
#  human_dtype      :string
#  direction        :string
#  level            :integer
#  human_level      :string
#  study_form       :integer
#  human_study_form :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  full_direction   :string
#  code             :string
#  profile          :string
#  qualification    :string
#  department_id    :integer
#  sae_id           :integer
#

class Specialty < ApplicationRecord
  has_many :link_specialty_disciplines
  has_many :disciplines, -> { distinct }, through: :link_specialty_disciplines
  belongs_to :department
  belongs_to :sae

  ### Scopes
  scope :directions, -> { group(:direction, :human_level, :code)
    .joins("LEFT JOIN saes ON saes.id = specialties.sae_id")
    .select("
      direction, human_level, code,
      COALESCE(string_agg(DISTINCT saes.short_name, ', '), '') as saes,
      COUNT(direction) as specialty_count
    ")
  }

  scope :with_term_number, -> { joins(:link_specialty_disciplines).select("specialties.*, count(distinct link_specialty_disciplines.term_number) as terms_count").group(:id) }
  scope :with_sae, -> { joins("LEFT JOIN saes ON saes.id = specialties.sae_id").select("saes.short_name as sae_short_name").group("saes.short_name") }

  def sae_name
    sae.present? ? sae.name : ""
  end

  def sae_short_name
    sae.present? ? sae.short_name : ""
  end

  # def saes
  #   if department_id
  #     Sae.joins("INNER JOIN departments_saes ON departments_saes.sae_id = saes.id").where("departments_saes.department_id = #{department_id}")
  #   else
  #     []
  #   end
  # end

  # def sae_string
  #   if saes.pluck(:name).present?
  #     saes.pluck(:name).join('; ')
  #   else
  #     " - "
  #   end
  # end
end

app/controllers/api/specialties_controller.rb
module Api
  class SpecialtiesController < ApplicationController

    before_action :get_group_list, only: :group_list

    def index
      filter = filter_params
      render json: Specialty.where(filter).to_json(methods: [:sae_name, :sae_short_name])
    end

    def group_list
      render json: @group_list

    end

    def search
      query = params[:query]
      @specialties = case
      when query.present?
        Specialty.where("profile ILIKE ? OR direction ILIKE ? OR code ILIKE ?", *["%#{query}%"]*3)
      else
        []
      end

      if query.present? && params[:human_levels].present?
        human_levels = params[:human_levels].map {|hl| "%#{hl}%"}
        @specialties = @specialties.where("human_level ILIKE ANY(array[?])", human_levels)
      end

      render json: @specialties.to_json(methods: [:sae_short_name])
    end

    def disciplines
      @specialty = Specialty.find(params[:id])
      render json: @specialty.disciplines.with_links_by_params(specialty_id: params[:id]).map(&:attributes)
    end

    private
    def get_group_list
      # grouped_directions = Specialty.directions.count(:direction).map(&:flatten).sort.group_by {|s| s[1]}
      grouped_directions = Specialty.directions.map(&:attributes).group_by {|s| s["human_level"]}
      sort_order = ["Бакалавриат", "Магистратура", "Специалитет", "Аспирантура"]
      @group_list = ApplicationController.helpers.custom_sort_by(grouped_directions, 0, sort_order).to_h
      # @group_list = grouped_directions.reduce({}) {|hash, (k, v)| hash.merge({k => v.map{ |f| { direction: f[0], code: f[2], specialty_count: f[3]}}})}
    end

    def filter_params
      permitted_params = [:id, :dtype, :human_dtype, :direction, :level, :human_level, :study_form, :human_study_form, :created_at, :updated_at, :full_direction, :code, :profile, :qualification]

      params.slice(*permitted_params).permit(permitted_params)
    end

  end
end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  before_action :set_specialty, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def compare
    @ids = [params[:id], params[:comparison_id]]
    @specialties = Specialty.with_term_number.with_sae.where(id: @ids)
    @specialties = ApplicationController.helpers.custom_sort_by(@specialties, 'id', @ids.map(&:to_i))
    @terms_count = @specialties.map(&:terms_count).max
  end

  # GET /specialties
  # GET /specialties.json
  def index
      # natural_science_cond = "disciplines.label ILIKE '%-ЕНМ.%'"
      # humanities_cond = "disciplines.label ILIKE '%-ГМ.%'"
      # # limit 50 records
      # @specialties = Specialty.joins(:disciplines).where("#{natural_science_cond} OR #{humanities_cond}").distinct.limit(50)
      # @specialties = @specialties.where("full_direction ilike ?", '%' + params['full_direction'].to_s + '%') if params['full_direction'].present?
      # @specialties = @specialties.where("level = ?", params['level'].to_s) if params['level'].present?
      # @specialties = @specialties.where("study_form = ?", params['study_form'].to_s) if params['study_form'].present?
  end

  # GET /specialties/1
  # GET /specialties/1.json
  def show
  end

  # GET /specialties/new
  def new
    @specialty = Specialty.new
  end

  # GET /specialties/1/edit
  def edit
  end

  # POST /specialties
  # POST /specialties.json
  def create
    @specialty = Specialty.new(specialty_params)

    respond_to do |format|
      if @specialty.save
        format.html { redirect_to @specialty, notice: 'Specialty was successfully created.' }
        format.json { render :show, status: :created, location: @specialty }
      else
        format.html { render :new }
        format.json { render json: @specialty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialties/1
  # PATCH/PUT /specialties/1.json
  def update
    respond_to do |format|
      if @specialty.update(specialty_params)
        format.html { redirect_to @specialty, notice: 'Specialty was successfully updated.' }
        format.json { render :show, status: :ok, location: @specialty }
      else
        format.html { render :edit }
        format.json { render json: @specialty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialties/1
  # DELETE /specialties/1.json
  def destroy
    @specialty.destroy
    respond_to do |format|
      format.html { redirect_to specialties_url, notice: 'Specialty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialty
      @specialty = Specialty.with_term_number.with_sae.find(params[:id])
      # @specialty = Specialty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialty_params
      params.require(:specialty).permit(:dtype, :human_dtype, :direction, :level, :human_level, :study_form, :human_study_form)
    end
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/views/specialties/_form.html.haml
= form_for @specialty do |f|
  - if @specialty.errors.any?
    #error_explanation
      %h2= "#{pluralize(@specialty.errors.count, "error")} prohibited this specialty from being saved:"
      %ul
        - @specialty.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :dtype
    = f.number_field :dtype
  .field
    = f.label :human_dtype
    = f.text_field :human_dtype
  .field
    = f.label :direction
    = f.text_field :direction
  .field
    = f.label :full_direction
    = f.text_field :full_direction
  .field
    = f.label :level
    = f.number_field :level
  .field
    = f.label :human_level
    = f.text_field :human_level
  .field
    = f.label :study_form
    = f.number_field :study_form
  .field
    = f.label :human_study_form
    = f.text_field :human_study_form
  .actions
    = f.submit 'Save'

app/views/specialties/_specialty.html.haml
.row.specialty-row.hover-highlight{"data-id" => "#{specialty.id}"}
  .card.card-outline-warning
    .card-block
      %blockquote.card-blockquote
        %div
          = link_to "#{specialty.full_direction}", specialty
        %div
          =specialty.human_level
          \|
          =specialty.human_study_form
        - if current_user
          %footer
            = link_to 'Редактировать', edit_specialty_path(specialty)
            = link_to 'Удалить', specialty, class: 'delete-link', :method => :delete, :data => { :confirm => "Удалить #{specialty.full_direction}?" }

  %div{id: "list-#{specialty.id}", class: "disciplines-list"}

app/views/specialties/compare.html.haml
= react_component 'CompareSpecialtyApp', specialties: @specialties, specialty_ids: @ids, terms_count: @terms_count

app/views/specialties/edit.html.haml
%h1 Editing specialty

= render 'form'

= link_to 'Show', @specialty
\|
= link_to 'Back', specialties_path

app/views/specialties/index.html.haml
/ .section
/   %h1.mb-2
/     Список специальностей

/   = render 'partials/search_form'

/   .row.table-title
/   #accordion
/     - @specialties.each do |specialty|
/       .row
/         = render specialty

/ = link_to 'New Specialty', new_specialty_path

/ = react_component 'SpecialtiesApp'

app/views/specialties/new.html.haml
%h1 New specialty

= render 'form'

= link_to 'Back', specialties_path

app/views/specialties/show.html.haml
/ %p#notice= notice

/ %p
/   %b Dtype:
/   = @specialty.dtype
/ %p
/   %b Human dtype:
/   = @specialty.human_dtype
/ %p
/   %b Direction:
/   = @specialty.direction
/ %p
/   %b Full direction:
/   = @specialty.full_direction
/ %p
/   %b Level:
/   = @specialty.level
/ %p
/   %b Human level:
/   = @specialty.human_level
/ %p
/   %b Study form:
/   = @specialty.study_form
/ %p
/   %b Human study form:
/   = @specialty.human_study_form

/ - if current_user
/   = link_to 'Edit', edit_specialty_path(@specialty)
/   \|
/   = link_to 'Back', specialties_path

= react_component 'SpecialtyApp', specialty: @specialty